### ISSUE TITLE
Web UI Development

### ISSUE THREAD

**Issue by Hornet004** [playproject-io/contracting#16]
## `@todo`
- [ ] Web UI Development
    - `@input` ❓ `final figma ui designs for new website` from #15 
    - `@output` ❓`new dat-ecosytem website`
    - `@output` ❓`new dat-ecosystem github page`

---

## `@info`
This is a summary of the main project issue that explains the project plan.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

great. same applies as my feedback on the previous issues.
What is missing here is where exactly is the `final figma ui designs for new website` coming from?

In which issue was that produces as an output ...there is a `from` missing here :-)

**Comment by Hornet004** [comment]
**worklog `2022.04.27`**

**Comment by serapath** [comment]
merged into #49
