### ISSUE TITLE
Present finished project

### ISSUE THREAD

**Issue by Helenphina** [playproject-io/contracting#31]
## `@todo`

- [ ] Presentation of dat ecosystem website
  * `@input`❓`Link to a working high fidelity design` from #22 
   * `@output`❓🏁`a 3-5 minutes video Screencast`
   

## `@info`
Here, a video Screencast will be made to show how the implemented dat ecosystem website is working. So as to ensure that all the features of the website are fully functioning.

**Comment by serapath** [comment]
**feedback `2022.04.27`**

nice :-) ...same little thing with the `from #22` after the `@input` to indicate where its from **and** maybe the video screencast can have a :checkered_flag: too

**Comment by serapath** [comment]
merged into #49
