### ISSUE TITLE
New dat-ecosystem website project plan

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#37]
## `@todo`

- **Steps to plan for the dat-ecosystem website**
    - [x] #38 
    - [x] #39 
    - [x] #40
    - [x] #41
    - [x] #42
    - [x] #43
    - [x] #48 
    - [x] #44
---
## `@info`
The above is a roadmap that was created for the dat ecosystem website

**Comment by serapath** [comment]
**feedback `2022.04.28`**

looks good to me

**Comment by serapath** [comment]
merged into #49
