### ISSUE TITLE
Web UI Implementation

### ISSUE THREAD

**Issue by CodeLawd** [playproject-io/contracting#42]
## `@todo`
 - [ ] UI Design Implementation (3 weeks)
    - `@input` :question: `Link to the final figma design` from #41 
    - `@output` :question: `A working website design (dat ecosystem website)`
 - Next #43
 
## `@info`
The website is being built by software developers to create a functioning website

**Comment by serapath** [comment]
**feedback `2022.04.28`**

same as in https://github.com/playproject-io/contracting/issues/45#issuecomment-1112698703

but there is a `from` field for an output  ...which points again at some sort of loop.

I would recommend to rather create another issue like **`Web UI Refinement`** that is  planned and comes **after** the validation and testing phase to avoid loops.

So what is needed is a specific form in which the results in the validation and testing task are captured as an output document and then it will say as a bullet point below that task `next #<issue_number_for_webUI_refinement>` and in the web UI refinement issue the todo list will have an issue: "refine UI based on user feedback" and a sub bullet point with `@input` :question: `user feedback document` from #43

**Comment by serapath** [comment]
merged into #49
